/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as ExecutionsRouteImport } from './routes/executions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesNewRouteImport } from './routes/sources/new'
import { Route as SourcesAddRouteImport } from './routes/sources/add'
import { Route as SourcesSourceIdRouteImport } from './routes/sources/$source-id'
import { Route as SourcesSourceIdEditRouteImport } from './routes/sources/$source-id.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsRoute = ExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNewRoute = SourcesNewRouteImport.update({
  id: '/sources/new',
  path: '/sources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesAddRoute = SourcesAddRouteImport.update({
  id: '/sources/add',
  path: '/sources/add',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$source-id',
  path: '/sources/$source-id',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdEditRoute = SourcesSourceIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SourcesSourceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/sources/$source-id': typeof SourcesSourceIdRouteWithChildren
  '/sources/add': typeof SourcesAddRoute
  '/sources/new': typeof SourcesNewRoute
  '/sources/$source-id/edit': typeof SourcesSourceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/sources/$source-id': typeof SourcesSourceIdRouteWithChildren
  '/sources/add': typeof SourcesAddRoute
  '/sources/new': typeof SourcesNewRoute
  '/sources/$source-id/edit': typeof SourcesSourceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/sources/$source-id': typeof SourcesSourceIdRouteWithChildren
  '/sources/add': typeof SourcesAddRoute
  '/sources/new': typeof SourcesNewRoute
  '/sources/$source-id/edit': typeof SourcesSourceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/executions'
    | '/secrets'
    | '/settings'
    | '/sources/$source-id'
    | '/sources/add'
    | '/sources/new'
    | '/sources/$source-id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/executions'
    | '/secrets'
    | '/settings'
    | '/sources/$source-id'
    | '/sources/add'
    | '/sources/new'
    | '/sources/$source-id/edit'
  id:
    | '__root__'
    | '/'
    | '/executions'
    | '/secrets'
    | '/settings'
    | '/sources/$source-id'
    | '/sources/add'
    | '/sources/new'
    | '/sources/$source-id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecutionsRoute: typeof ExecutionsRoute
  SecretsRoute: typeof SecretsRoute
  SettingsRoute: typeof SettingsRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRouteWithChildren
  SourcesAddRoute: typeof SourcesAddRoute
  SourcesNewRoute: typeof SourcesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions': {
      id: '/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof ExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/new': {
      id: '/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof SourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/add': {
      id: '/sources/add'
      path: '/sources/add'
      fullPath: '/sources/add'
      preLoaderRoute: typeof SourcesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$source-id': {
      id: '/sources/$source-id'
      path: '/sources/$source-id'
      fullPath: '/sources/$source-id'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$source-id/edit': {
      id: '/sources/$source-id/edit'
      path: '/edit'
      fullPath: '/sources/$source-id/edit'
      preLoaderRoute: typeof SourcesSourceIdEditRouteImport
      parentRoute: typeof SourcesSourceIdRoute
    }
  }
}

interface SourcesSourceIdRouteChildren {
  SourcesSourceIdEditRoute: typeof SourcesSourceIdEditRoute
}

const SourcesSourceIdRouteChildren: SourcesSourceIdRouteChildren = {
  SourcesSourceIdEditRoute: SourcesSourceIdEditRoute,
}

const SourcesSourceIdRouteWithChildren = SourcesSourceIdRoute._addFileChildren(
  SourcesSourceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecutionsRoute: ExecutionsRoute,
  SecretsRoute: SecretsRoute,
  SettingsRoute: SettingsRoute,
  SourcesSourceIdRoute: SourcesSourceIdRouteWithChildren,
  SourcesAddRoute: SourcesAddRoute,
  SourcesNewRoute: SourcesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
