/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as SecretsRouteImport } from "./routes/secrets";
import { Route as ExecutionsRouteImport } from "./routes/executions";
import { Route as SourcesAddRouteImport } from "./routes/sources/add";
import { Route as SourcesNewRouteImport } from "./routes/sources/new";
import { Route as SourcesSourceIdRouteImport } from "./routes/sources/$source-id";
import { Route as SourcesSourceIdEditRouteImport } from "./routes/sources/$source-id.edit";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);

const SecretsRoute = SecretsRouteImport.update({
  id: "/secrets",
  path: "/secrets",
  getParentRoute: () => rootRouteImport,
} as any);

const ExecutionsRoute = ExecutionsRouteImport.update({
  id: "/executions",
  path: "/executions",
  getParentRoute: () => rootRouteImport,
} as any);

const SourcesAddRoute = SourcesAddRouteImport.update({
  id: "/sources/add",
  path: "/sources/add",
  getParentRoute: () => rootRouteImport,
} as any);

const SourcesNewRoute = SourcesNewRouteImport.update({
  id: "/sources/new",
  path: "/sources/new",
  getParentRoute: () => rootRouteImport,
} as any);

const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: "/sources/$sourceId",
  path: "/sources/$sourceId",
  getParentRoute: () => rootRouteImport,
} as any);

const SourcesSourceIdEditRoute = SourcesSourceIdEditRouteImport.update({
  id: "/sources/$sourceId/edit",
  path: "/sources/$sourceId/edit",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/secrets": typeof SecretsRoute;
  "/executions": typeof ExecutionsRoute;
  "/sources/add": typeof SourcesAddRoute;
  "/sources/new": typeof SourcesNewRoute;
  "/sources/$sourceId": typeof SourcesSourceIdRoute;
  "/sources/$sourceId/edit": typeof SourcesSourceIdEditRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/secrets": typeof SecretsRoute;
  "/executions": typeof ExecutionsRoute;
  "/sources/add": typeof SourcesAddRoute;
  "/sources/new": typeof SourcesNewRoute;
  "/sources/$sourceId": typeof SourcesSourceIdRoute;
  "/sources/$sourceId/edit": typeof SourcesSourceIdEditRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/secrets": typeof SecretsRoute;
  "/executions": typeof ExecutionsRoute;
  "/sources/add": typeof SourcesAddRoute;
  "/sources/new": typeof SourcesNewRoute;
  "/sources/$sourceId": typeof SourcesSourceIdRoute;
  "/sources/$sourceId/edit": typeof SourcesSourceIdEditRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/secrets"
    | "/executions"
    | "/sources/add"
    | "/sources/new"
    | "/sources/$sourceId"
    | "/sources/$sourceId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings"
    | "/secrets"
    | "/executions"
    | "/sources/add"
    | "/sources/new"
    | "/sources/$sourceId"
    | "/sources/$sourceId/edit";
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/secrets"
    | "/executions"
    | "/sources/add"
    | "/sources/new"
    | "/sources/$sourceId"
    | "/sources/$sourceId/edit";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  SecretsRoute: typeof SecretsRoute;
  ExecutionsRoute: typeof ExecutionsRoute;
  SourcesAddRoute: typeof SourcesAddRoute;
  SourcesNewRoute: typeof SourcesNewRoute;
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute;
  SourcesSourceIdEditRoute: typeof SourcesSourceIdEditRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SecretsRoute: SecretsRoute,
  ExecutionsRoute: ExecutionsRoute,
  SourcesAddRoute: SourcesAddRoute,
  SourcesNewRoute: SourcesNewRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  SourcesSourceIdEditRoute: SourcesSourceIdEditRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
